eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niumoo/config-repo
          username: niumoo@126.com
          password: Asd839819864
          basedir: D:\IdeaProjectMy\springcloud\config\basedir
  rabbitmq:
    host: 192.168.131.138
# \u66B4\u6F0F\u7AEF\u53E3
management:
  endpoints:
    web:
      exposure:
        include: "*"
#      cors:
#        allowed-methods: "*"
#        allowed-headers: "*"
#        allowed-origins: "*"