eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    inetutils:
      timeout-seconds: 10
  application:
    name: eureka-client

server:
  port: 8081