eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  server:
  #eureka 的自我保护，开发环境可以环比
    #enable-self-preservation: false
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: eureka
server:
 port: 8761

